# Dependencies

highlighter:      rouge
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Random Stuff
tagline:          'Read with caution'
description:      'Just some guy just thinking of things and dumping them here.'
url:              http://ogbinar.com
baseurl:          http://ogbinar.github.io/

author:
  name:           'Myk'
  url:            https://twitter.com/ogbinar

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/ogbinar
