# Dependencies

highlighter:      rouge
plugins: [jekyll-paginate,jekyll-seo-tag, jekyll-sitemap]]
google_analytics: 'UA-2474755-2'

# Permalinks
permalink:        pretty

# Setup
title:            Random Stuff
tagline:          'Read with caution'
description:      'Just some guy just thinking of things and dumping them here.'
url:              http://ogbinar.com
baseurl:          http://ogbinar.github.io/

author:
  name:           'Myk'
  url:            https://twitter.com/ogbinar

paginate:         5

# Custom vars
version:          0.1

link:
  
  email:    mailto:myk.ogbinar@yahoo.com.ph
  linkedin: https://www.linkedin.com/in/ogbinar/  
  github:           https://github.com/ogbinar
  facebook: https://www.facebook.com/ogbinar
  steam:    https://steamcommunity.com/profiles/76561198028150606/
  instagram:    https://www.instagram.com/ogbinar/
  twitter:  https://twitter.com/ogbinar