# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Pseudo Random Generator
tagline:          'Read with caution'
description:      'Some guy just thinking of things and dumping them here.'
url:              http://ogbinar.com
baseurl:          /

author:
  name:           'Myk'
  url:            https://twitter.com/ogbinar

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ogbinar
