---
title: "Michel Learns to Code"
about:
    template: jolla
    links:
        - icon: linkedin
          text: LinkedIn
          href: https://www.linkedin.com/in/ogbinar/
        - icon: github
          text: Github
          url: https://github.com/ogbinar
        - icon: envelope
          text: Email
          href: mailto:myk.ogbinar+internet@gmail.com

 
comments: false
---

## Bio

I am a data specialist, currently working in a conglomerate in the Philippines. I'm in my 2nd year of being a PhD student of Artificial Intelligence. My research interests are in unstructured data, particularly computer vision, multi-modal models, large language and vision models, and remote sensing / geosatellite applications of machine learning. On the side, I teach / mentor about Data Science in FTW Foundation. I manage a tech data community, Data Engineering Pilipinas. One of my goals is to eventually build a completely free and open source learning material on data skills that will enable free or cheaper data bootcamps in the Philippines.

## Projects
- [Data Engineering Pilipinas](https://github.com/ogbinar/DataEngineeringPilipinas)
- [Learn Data Skills - Free & Open Source Data Skills Reference](https://learndataskills.ph)
